### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by MasonChinkin** [MasonChinkin/availableFlatSurface#6]
- [ ] put user review at top of reviews
- [ ] edit/delete reviews
- [ ] fix restaurant show page reservation form
- [ ] better way to show new reservation to user
- [ ] fix negative times on profile
- [ ] fix splash search form time not persisting if not actively selected
- [ ] fix lifecycle issues, including save button, make/edit/delete review buttons
